workflows:
  ios-testflight:
    name: iOS TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.22.3
      xcode: latest
      cocoapods: default
      groups: []
      vars:
        APP_STORE_APPLE_ID: 6779357856
        BUNDLE_ID: app.chitatel.ios
    integrations:
      app_store_connect: chitatel-key
    scripts:
      - name: Get Flutter packages
        working_directory: app
        script: |
          flutter pub get
      - name: Install pods
        working_directory: app
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up signing certificate
        script: |
          keychain initialize
          app-store-connect certificates list \
            --type IOS_DISTRIBUTION \
            --certificate-key=@env:CERTIFICATE_PRIVATE_KEY \
            --save || keychain add-certificates
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        working_directory: app
        script: |
          xcode-project use-profiles
      - name: Flutter build ipa
        working_directory: app
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - app/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - app/flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false
